MCU = atmega32u4

CAPS_WORD_ENABLE = yes
UNICODE_ENABLE =  yes

TAP_DANCE_ENABLE = no
COMMAND_ENABLE = no
CONSOLE_ENABLE = no
BLUETOOTH_ENABLE = no
AUDIO_ENABLE = no
MIDI_ENABLE = no
SPACE_CADET_ENABLE = no
